import { strToU8, zipSync } from "fflate";

type PluginMessage =
  | { type: "selection"; valid: boolean; count: number; node: { id: string; name: string; type: string; width: number; height: number } | null }
  | { type: "start"; name: string }
  | { type: "progress"; message: string }
  | { type: "file"; path: string; bytes: Uint8Array | number[]; source: string }
  | { type: "done"; name: string; json: string; stats: Record<string, number> }
  | { type: "error"; message: string };

function element<T extends Element>(selector: string) {
  const target = document.querySelector<T>(selector);
  if (!target) throw new Error(`Plugin UI is missing ${selector}.`);
  return target;
}

const exportButton = element<HTMLButtonElement>("#export");
const selectionTitle = element<HTMLElement>("#selection-title");
const selectionMeta = element<HTMLElement>("#selection-meta");
const status = element<HTMLElement>("#status");
const progress = element<HTMLElement>("#progress");
const stats = element<HTMLElement>("#stats");
const optionsForm = element<HTMLFormElement>("#options");

let files: Record<string, Uint8Array> = {};

function setBusy(busy: boolean) {
  exportButton.disabled = busy || exportButton.dataset.selectionValid !== "true";
  optionsForm.querySelectorAll<HTMLInputElement>("input").forEach((input) => {
    input.disabled = busy;
  });
  progress.classList.toggle("is-active", busy);
}

function option(name: string) {
  return Boolean(optionsForm.querySelector<HTMLInputElement>(`[name="${name}"]`)?.checked);
}

exportButton.addEventListener("click", () => {
  files = {};
  stats.textContent = "";
  status.textContent = "Starting export…";
  setBusy(true);
  parent.postMessage(
    {
      pluginMessage: {
        type: "export",
        options: {
          includeHidden: option("includeHidden"),
          includeConfiguredExports: option("includeConfiguredExports"),
          includeVectors: option("includeVectors"),
          includePreview: option("includePreview"),
          includeVariables: option("includeVariables"),
          includeCss: option("includeCss")
        }
      }
    },
    "*"
  );
});

window.onmessage = (event: MessageEvent<{ pluginMessage: PluginMessage }>) => {
  const message = event.data.pluginMessage;
  if (!message) return;

  if (message.type === "selection") {
    exportButton.dataset.selectionValid = String(message.valid);
    exportButton.disabled = !message.valid;
    if (message.node) {
      selectionTitle.textContent = message.node.name;
      selectionMeta.textContent = `${message.node.type} · ${message.node.width} × ${message.node.height} · ${message.node.id}`;
    } else {
      selectionTitle.textContent = "Select one case-study frame";
      selectionMeta.textContent = message.count ? `${message.count} layers selected` : "Nothing selected";
    }
    status.textContent = message.valid ? "Ready to export" : "Select one frame, section, component, instance, or group.";
  }

  if (message.type === "start") {
    files = {};
    status.textContent = `Reading ${message.name}…`;
    setBusy(true);
  }

  if (message.type === "progress") status.textContent = message.message;

  if (message.type === "file") {
    files[message.path] = message.bytes instanceof Uint8Array ? message.bytes : new Uint8Array(message.bytes);
  }

  if (message.type === "done") {
    status.textContent = "Building ZIP…";
    files["design.json"] = strToU8(message.json);
    files["README.txt"] = strToU8(
      "Generated by Case Study Package Exporter.\n\n" +
        "design.json contains the selected Figma node tree, styles, variables, and asset mappings.\n" +
        "assets/images contains original image-fill bytes.\n" +
        "assets/exports contains nodes with Figma export settings.\n" +
        "assets/vectors contains optional SVG vector exports.\n" +
        "screenshots contains the selected-frame reference PNG.\n"
    );

    try {
      const zipped = zipSync(files, { level: 6 });
      const blob = new Blob([zipped], { type: "application/zip" });
      const link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download = `${message.name}.zip`;
      link.click();
      window.setTimeout(() => URL.revokeObjectURL(link.href), 1000);
      status.textContent = "ZIP downloaded";
      stats.textContent = `${message.stats.nodeCount} layers · ${message.stats.imageFillCount} images · ${message.stats.configuredExportCount} configured exports · ${message.stats.vectorExportCount} vectors`;
    } catch (error) {
      status.textContent = `Could not build ZIP: ${String(error)}`;
    }
    setBusy(false);
  }

  if (message.type === "error") {
    status.textContent = message.message;
    setBusy(false);
  }
};
